spring.application.name=royal-curtains-store-management
server.port=8080

# PostgreSQL settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/royal_curtains}
spring.datasource.username=${DB_USERNAME:saeedsekandari}
spring.datasource.password=${DB_PASSWORD:}

# Create and update database tables automatically during development
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Show updated pages immediately while developing
spring.thymeleaf.cache=false